CREATE DATABASE PRACTICE_QUESTION;
USE PRACTICE_QUESTION;
CREATE TABLE TRANSACTION(
	PAYMENT INT,
    CUSTOMER VARCHAR(50),
    MODE VARCHAR(20),
    CITY VARCHAR(20)
);
INSERT INTO TRANSACTION(PAYMENT, CUSTOMER, MODE, CITY) VALUES 
(101, "OLIVIA BARRETT", "NETBANKING", "PORTLAND"),
(102, "ETHAN SINCLAIR", "CREDIT CARD", "MIAMI"),
(103, "MAYA HERNANDEZ", "CREDIT CARD", "SEATTLE"),
(104, "LIAM DONOVAN", "NETBANKING", "DENVER"),
(105, "SOPHIA NGUYEN", "CREDIT CARD", "NEW ORLEANS"),
(106, "CALEB FOSTER", "DEBIT CARD", "MINNEAPOLIS"),
(107, "AVA PATEL", "DEBIT CARD", "PHOENIX"),
(108, "LUCAS CARTER", "NETBANKING", "BOSTON"),
(109, "ISSABELLA MARTINEZ", "NETBANKING", "NASHVILLE"),
(110, "JACKSON BROOKS", "CREDIT CARD", "BOSTON");
SELECT MODE, COUNT(PAYMENT) FROM TRANSACTION GROUP BY MODE;