USE COLLEGE;
CREATE TABLE STUDENT2(
	ROLLNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    MARKS INT,
    GRADE VARCHAR(1),
    STATE VARCHAR(20)
);
INSERT INTO STUDENT2(ROLLNO, NAME, MARKS, GRADE, STATE) VALUE
(101, "AMAN", 91, "B", "RAJASTHAN"),
(102, "DIPEN", 89, "A", "PUNJAB"),
(103, "RIYA", 100, "A", "RAJASTHAN"),
(104, "KISHOR", 69, "C", "DELHI"),
(105, "KISHAN", 88, "B", "DELHI"),
(106, "VIJAY", 72, "A", "DELHI");
SELECT STATE, AVG(MARKS) FROM STUDENT2 GROUP BY STATE ORDER BY AVG(MARKS) DESC;